//
//  UnitIdentifierExtension.swift
//  Bluetooth
//
//  Generated by Carlos Duclos on 6/11/18.
//

public extension UnitIdentifier {
    
    /// electric resistance (ohm) (`0x272A`)
    static var electricResistance: UnitIdentifier {
        return UnitIdentifier(rawValue: 0x272A)
    }
    
    /// power (watt) (`0x2726`)
    static var power: UnitIdentifier {
        return UnitIdentifier(rawValue: 0x2726)
    }
    
    /// length (inch) (`0x27A2`)
    static var inch: UnitIdentifier {
        return UnitIdentifier(rawValue: 0x27A2)
    }
    
    /// mass (tonne) (`0x2768`)
    static var tonne: UnitIdentifier {
        return UnitIdentifier(rawValue: 0x2768)
    }
    
    /// length (ngstrm) (`0x2782`)
    static var ngstrm: UnitIdentifier {
        return UnitIdentifier(rawValue: 0x2782)
    }
    
    /// time (hour) (`0x2761`)
    static var hour: UnitIdentifier {
        return UnitIdentifier(rawValue: 0x2761)
    }
    
    /// velocity (mile per hour) (`0x27A7`)
    static var milePerHour: UnitIdentifier {
        return UnitIdentifier(rawValue: 0x27A7)
    }
    
    /// electric charge density (coulomb per cubic metre) (`0x274C`)
    static var electricChargeDensity: UnitIdentifier {
        return UnitIdentifier(rawValue: 0x274C)
    }
    
    /// refractive index (`0x271D`)
    static var refractiveIndex: UnitIdentifier {
        return UnitIdentifier(rawValue: 0x271D)
    }
    
    /// per mille (`0x27AE`)
    static var perMille: UnitIdentifier {
        return UnitIdentifier(rawValue: 0x27AE)
    }
    
    /// mass (kilogram) (`0x2702`)
    static var kilogram: UnitIdentifier {
        return UnitIdentifier(rawValue: 0x2702)
    }
    
    /// plane angle (minute) (`0x2764`)
    static var planeAngleMinute: UnitIdentifier {
        return UnitIdentifier(rawValue: 0x2764)
    }
    
    /// energy (joule) (`0x2725`)
    static var energy: UnitIdentifier {
        return UnitIdentifier(rawValue: 0x2725)
    }
    
    /// energy (kilogram calorie) (`0x27AA`)
    static var kilogramCalorie: UnitIdentifier {
        return UnitIdentifier(rawValue: 0x27AA)
    }
    
    /// amount of substance (mole) (`0x2706`)
    static var mole: UnitIdentifier {
        return UnitIdentifier(rawValue: 0x2706)
    }
    
    /// length (metre) (`0x2701`)
    static var metre: UnitIdentifier {
        return UnitIdentifier(rawValue: 0x2701)
    }
    
    /// catalytic activity concentration (katal per cubic metre) (`0x2757`)
    static var catalyticActivity: UnitIdentifier {
        return UnitIdentifier(rawValue: 0x2757)
    }
    
    /// velocity (knot) (`0x2785`)
    static var velocityKnot: UnitIdentifier {
        return UnitIdentifier(rawValue: 0x2785)
    }
    
    /// stroke (per minute) (`0x27BC`)
    static var stroke: UnitIdentifier {
        return UnitIdentifier(rawValue: 0x27BC)
    }
    
    /// concentration (count per cubic metre) (`0x27B5`)
    static var concentration: UnitIdentifier {
        return UnitIdentifier(rawValue: 0x27B5)
    }
    
    /// electric current (ampere) (`0x2704`)
    static var ampere: UnitIdentifier {
        return UnitIdentifier(rawValue: 0x2704)
    }
    
    /// luminous efficacy (lumen per watt) (`0x27BE`)
    static var luminousEfficacy: UnitIdentifier {
        return UnitIdentifier(rawValue: 0x27BE)
    }
    
    /// capacitance (farad) (`0x2729`)
    static var capitance: UnitIdentifier {
        return UnitIdentifier(rawValue: 0x2729)
    }
    
    /// activity referred to a radionuclide (becquerel) (`0x2732`)
    static var becquerel: UnitIdentifier {
        return UnitIdentifier(rawValue: 0x2732)
    }
    
    /// plane angle (degree) (`0x2763`)
    static var degree: UnitIdentifier {
        return UnitIdentifier(rawValue: 0x2763)
    }
    
    /// illuminance (lux) (`0x2731`)
    static var illuminance: UnitIdentifier {
        return UnitIdentifier(rawValue: 0x2731)
    }
    
    /// magnetic flux (weber) (`0x272C`)
    static var magneticFlux: UnitIdentifier {
        return UnitIdentifier(rawValue: 0x272C)
    }
    
    /// current density (ampere per square metre) (`0x2718`)
    static var currentDensity: UnitIdentifier {
        return UnitIdentifier(rawValue: 0x2718)
    }
    
    /// time (second) (`0x2703`)
    static var second: UnitIdentifier {
        return UnitIdentifier(rawValue: 0x2703)
    }
    
    /// molar energy (joule per mole) (`0x2751`)
    static var molarEnergy: UnitIdentifier {
        return UnitIdentifier(rawValue: 0x2751)
    }
    
    /// irradiance (watt per square metre) (`0x27B6`)
    static var irrandiance: UnitIdentifier {
        return UnitIdentifier(rawValue: 0x27B6)
    }
    
    /// electric field strength (volt per metre) (`0x274B`)
    static var electricFieldStrength: UnitIdentifier {
        return UnitIdentifier(rawValue: 0x274B)
    }
    
    /// pace (kilometre per minute) (`0x27BD`)
    static var pace: UnitIdentifier {
        return UnitIdentifier(rawValue: 0x27BD)
    }
    
    /// pressure (bar) (`0x2780`)
    static var bar: UnitIdentifier {
        return UnitIdentifier(rawValue: 0x2780)
    }
    
    /// specific energy (joule per kilogram) (`0x2748`)
    static var specificEnergy: UnitIdentifier {
        return UnitIdentifier(rawValue: 0x2748)
    }
    
    /// acceleration (metres per second squared) (`0x2713`)
    static var acceleration: UnitIdentifier {
        return UnitIdentifier(rawValue: 0x2713)
    }
    
    /// angular velocity (revolution per minute) (`0x27A8`)
    static var revolutionPerMinute: UnitIdentifier {
        return UnitIdentifier(rawValue: 0x27A8)
    }
    
    /// catalytic activity (katal) (`0x2735`)
    static var katal: UnitIdentifier {
        return UnitIdentifier(rawValue: 0x2735)
    }
    
    /// radiance (watt per square metre steradian) (`0x2756`)
    static var radiance: UnitIdentifier {
        return UnitIdentifier(rawValue: 0x2756)
    }
    
    /// mass concentration (kilogram per cubic metre) (`0x271B`)
    static var massConcentration: UnitIdentifier {
        return UnitIdentifier(rawValue: 0x271B)
    }
    
    /// heat flux density (watt per square metre) (`0x2745`)
    static var heatFluxDensity: UnitIdentifier {
        return UnitIdentifier(rawValue: 0x2745)
    }
    
    /// time (month) (`0x27B4`)
    static var month: UnitIdentifier {
        return UnitIdentifier(rawValue: 0x27B4)
    }
    
    /// velocity (metres per second) (`0x2712`)
    static var velocity: UnitIdentifier {
        return UnitIdentifier(rawValue: 0x2712)
    }
    
    /// radiant intensity (watt per steradian) (`0x2755`)
    static var radradiantIntensityiance: UnitIdentifier {
        return UnitIdentifier(rawValue: 0x2755)
    }
    
    /// dynamic viscosity (pascal second) (`0x2740`)
    static var pascalSecond: UnitIdentifier {
        return UnitIdentifier(rawValue: 0x2740)
    }
    
    /// energy (gram calorie) (`0x27A9`)
    static var gramCalorie: UnitIdentifier {
        return UnitIdentifier(rawValue: 0x27A9)
    }
    
    /// mass flow (gram per second) (`0x27C1`)
    static var massFlow: UnitIdentifier {
        return UnitIdentifier(rawValue: 0x27C1)
    }
    
    /// relative permeability (`0x271E`)
    static var relativePermeability: UnitIdentifier {
        return UnitIdentifier(rawValue: 0x271E)
    }
    
    /// electric conductance (siemens) (`0x272B`)
    static var electricConductance: UnitIdentifier {
        return UnitIdentifier(rawValue: 0x272B)
    }
    
    /// volume (litre) (`0x2767`)
    static var litre: UnitIdentifier {
        return UnitIdentifier(rawValue: 0x2767)
    }
    
    /// dose equivalent (sievert) (`0x2734`)
    static var sievert: UnitIdentifier {
        return UnitIdentifier(rawValue: 0x2734)
    }
    
    /// plane angle (second) (`0x2765`)
    static var planeAngleSecond: UnitIdentifier {
        return UnitIdentifier(rawValue: 0x2765)
    }
    
    /// luminous energy (lumen hour) (`0x27BF`)
    static var luminousEnergy: UnitIdentifier {
        return UnitIdentifier(rawValue: 0x27BF)
    }
    
    /// absorbed dose rate (gray per second) (`0x2754`)
    static var absorbedDoseRate: UnitIdentifier {
        return UnitIdentifier(rawValue: 0x2754)
    }
    
    /// area (hectare) (`0x2766`)
    static var hectare: UnitIdentifier {
        return UnitIdentifier(rawValue: 0x2766)
    }
    
    /// force (newton) (`0x2723`)
    static var force: UnitIdentifier {
        return UnitIdentifier(rawValue: 0x2723)
    }
    
    /// pressure (pound-force per square inch) (`0x27A5`)
    static var pressurePoundForce: UnitIdentifier {
        return UnitIdentifier(rawValue: 0x27A5)
    }
    
    /// angular acceleration (radian per second squared) (`0x2744`)
    static var angularAcceleration: UnitIdentifier {
        return UnitIdentifier(rawValue: 0x2744)
    }
    
    /// volume (cubic metres) (`0x2711`)
    static var volume: UnitIdentifier {
        return UnitIdentifier(rawValue: 0x2711)
    }
    
    /// percentage (`0x27AD`)
    static var percentage: UnitIdentifier {
        return UnitIdentifier(rawValue: 0x27AD)
    }
    
    /// thermodynamic temperature (kelvin) (`0x2705`)
    static var kelvin: UnitIdentifier {
        return UnitIdentifier(rawValue: 0x2705)
    }
    
    /// pressure (pascal) (`0x2724`)
    static var pascalPressure: UnitIdentifier {
        return UnitIdentifier(rawValue: 0x2724)
    }
    
    /// logarithmic radio quantity (neper) (`0x2786`)
    static var neper: UnitIdentifier {
        return UnitIdentifier(rawValue: 0x2786)
    }
    
    /// length (parsec) (`0x27A1`)
    static var parsec: UnitIdentifier {
        return UnitIdentifier(rawValue: 0x27A1)
    }
    
    /// permittivity (farad per metre) (`0x274F`)
    static var permittivity: UnitIdentifier {
        return UnitIdentifier(rawValue: 0x274F)
    }
    
    /// logarithmic radio quantity (bel) (`0x2787`)
    static var bel: UnitIdentifier {
        return UnitIdentifier(rawValue: 0x2787)
    }
    
    /// step (per minute) (`0x27BA`)
    static var step: UnitIdentifier {
        return UnitIdentifier(rawValue: 0x27BA)
    }
    
    /// magnetic field strength (ampere per metre) (`0x2719`)
    static var magneticFieldStrengh: UnitIdentifier {
        return UnitIdentifier(rawValue: 0x2719)
    }
    
    /// mass density (milligram per decilitre) (`0x27B1`)
    static var milligramPerDecilitre: UnitIdentifier {
        return UnitIdentifier(rawValue: 0x27B1)
    }
    
    /// specific heat capacity (joule per kilogram kelvin) (`0x2747`)
    static var specificHeatCapacity: UnitIdentifier {
        return UnitIdentifier(rawValue: 0x2747)
    }
    
    /// amount concentration (mole per cubic metre) (`0x271A`)
    static var amountConcentration: UnitIdentifier {
        return UnitIdentifier(rawValue: 0x271A)
    }
    
    /// electric charge (coulomb) (`0x2727`)
    static var coulomb: UnitIdentifier {
        return UnitIdentifier(rawValue: 0x2727)
    }
    
    /// time (year) (`0x27B3`)
    static var year: UnitIdentifier {
        return UnitIdentifier(rawValue: 0x27B3)
    }
    
    /// length (nautical mile) (`0x2783`)
    static var nauticalMile: UnitIdentifier {
        return UnitIdentifier(rawValue: 0x2783)
    }
    
    /// surface density (kilogram per square metre) (`0x2716`)
    static var surfaceDensity: UnitIdentifier {
        return UnitIdentifier(rawValue: 0x2716)
    }
    
    /// solid angle (steradian) (`0x2721`)
    static var solidAngle: UnitIdentifier {
        return UnitIdentifier(rawValue: 0x2721)
    }
    
    /// surface tension (newton per metre) (`0x2742`)
    static var surfaceTension: UnitIdentifier {
        return UnitIdentifier(rawValue: 0x2742)
    }
    
    /// mass density (millimole per litre) (`0x27B2`)
    static var millimolePerLitre: UnitIdentifier {
        return UnitIdentifier(rawValue: 0x27B2)
    }
    
    /// magnetic flux density (tesla) (`0x272D`)
    static var magneticFluxDensity: UnitIdentifier {
        return UnitIdentifier(rawValue: 0x272D)
    }
    
    /// electric charge (ampere hours) (`0x27B0`)
    static var ampereHours: UnitIdentifier {
        return UnitIdentifier(rawValue: 0x27B0)
    }
    
    /// metabolic equivalent (`0x27B9`)
    static var metabolicEquivalent: UnitIdentifier {
        return UnitIdentifier(rawValue: 0x27B9)
    }
    
    /// luminous intensity (candela) (`0x2707`)
    static var candela: UnitIdentifier {
        return UnitIdentifier(rawValue: 0x2707)
    }
    
    /// plane angle (radian) (`0x2720`)
    static var planeAngle: UnitIdentifier {
        return UnitIdentifier(rawValue: 0x2720)
    }
    
    /// electric potential difference (volt) (`0x2728`)
    static var electricPotential: UnitIdentifier {
        return UnitIdentifier(rawValue: 0x2728)
    }
    
    /// thermodynamic temperature (degree Fahrenheit) (`0x27AC`)
    static var degreeFahrenheit: UnitIdentifier {
        return UnitIdentifier(rawValue: 0x27AC)
    }
    
    /// surface charge density (coulomb per square metre) (`0x274D`)
    static var surfaceChargeDensity: UnitIdentifier {
        return UnitIdentifier(rawValue: 0x274D)
    }
    
    /// heat capacity (joule per kelvin) (`0x2746`)
    static var heatCapacity: UnitIdentifier {
        return UnitIdentifier(rawValue: 0x2746)
    }
    
    /// unitless (`0x2700`)
    static var unitless: UnitIdentifier {
        return UnitIdentifier(rawValue: 0x2700)
    }
    
    /// specific volume (cubic metre per kilogram) (`0x2717`)
    static var specificVolume: UnitIdentifier {
        return UnitIdentifier(rawValue: 0x2717)
    }
    
    /// thermal conductivity (watt per metre kelvin) (`0x2749`)
    static var thermalConductivity: UnitIdentifier {
        return UnitIdentifier(rawValue: 0x2749)
    }
    
    /// wavenumber (reciprocal metre) (`0x2714`)
    static var wavenumber: UnitIdentifier {
        return UnitIdentifier(rawValue: 0x2714)
    }
    
    /// absorbed dose (gray) (`0x2733`)
    static var absorbedDose: UnitIdentifier {
        return UnitIdentifier(rawValue: 0x2733)
    }
    
    /// milliliter (per kilogram per minute) (`0x27B7`)
    static var millilitre: UnitIdentifier {
        return UnitIdentifier(rawValue: 0x27B7)
    }
    
    /// permeability (henry per metre) (`0x2750`)
    static var permeability: UnitIdentifier {
        return UnitIdentifier(rawValue: 0x2750)
    }
    
    /// area (square metres) (`0x2710`)
    static var area: UnitIdentifier {
        return UnitIdentifier(rawValue: 0x2710)
    }
    
    /// molar entropy (joule per mole kelvin) (`0x2752`)
    static var molarEntropy: UnitIdentifier {
        return UnitIdentifier(rawValue: 0x2752)
    }
    
    /// energy (kilowatt hour) (`0x27AB`)
    static var kilowattHour: UnitIdentifier {
        return UnitIdentifier(rawValue: 0x27AB)
    }
    
    /// luminance (candela per square metre) (`0x271C`)
    static var luminance: UnitIdentifier {
        return UnitIdentifier(rawValue: 0x271C)
    }
    
    /// luminous flux (lumen) (`0x2730`)
    static var luminousFlux: UnitIdentifier {
        return UnitIdentifier(rawValue: 0x2730)
    }
    
    /// energy density (joule per cubic metre) (`0x274A`)
    static var energyDensity: UnitIdentifier {
        return UnitIdentifier(rawValue: 0x274A)
    }
    
    /// electric flux density (coulomb per square metre) (`0x274E`)
    static var electricFluxDensity: UnitIdentifier {
        return UnitIdentifier(rawValue: 0x274E)
    }
    
    /// velocity (kilometre per hour) (`0x27A6`)
    static var kilometrePerHour: UnitIdentifier {
        return UnitIdentifier(rawValue: 0x27A6)
    }
    
    /// mass (pound) (`0x27B8`)
    static var pound: UnitIdentifier {
        return UnitIdentifier(rawValue: 0x27B8)
    }
    
    /// luminous exposure (lux hour) (`0x27C0`)
    static var luminousExposure: UnitIdentifier {
        return UnitIdentifier(rawValue: 0x27C0)
    }
    
    /// exposure (coulomb per kilogram) (`0x2753`)
    static var exposure: UnitIdentifier {
        return UnitIdentifier(rawValue: 0x2753)
    }
    
    /// time (minute) (`0x2760`)
    static var minute: UnitIdentifier {
        return UnitIdentifier(rawValue: 0x2760)
    }
    
    /// frequency (hertz) (`0x2722`)
    static var frequency: UnitIdentifier {
        return UnitIdentifier(rawValue: 0x2722)
    }
    
    /// moment of force (newton metre) (`0x2741`)
    static var newtonMetre: UnitIdentifier {
        return UnitIdentifier(rawValue: 0x2741)
    }
    
    /// Celsius temperature (degree Celsius) (`0x272F`)
    static var celsius: UnitIdentifier {
        return UnitIdentifier(rawValue: 0x272F)
    }
    
    /// time (day) (`0x2762`)
    static var day: UnitIdentifier {
        return UnitIdentifier(rawValue: 0x2762)
    }
    
    /// pressure (millimetre of mercury) (`0x2781`)
    static var millimetreOfMercury: UnitIdentifier {
        return UnitIdentifier(rawValue: 0x2781)
    }
    
    /// length (yard) (`0x27A0`)
    static var yard: UnitIdentifier {
        return UnitIdentifier(rawValue: 0x27A0)
    }
    
    /// volume flow (litre per second) (`0x27C2`)
    static var volumeFlow: UnitIdentifier {
        return UnitIdentifier(rawValue: 0x27C2)
    }
    
    /// length (foot) (`0x27A3`)
    static var foot: UnitIdentifier {
        return UnitIdentifier(rawValue: 0x27A3)
    }
    
    /// angular velocity (radian per second) (`0x2743`)
    static var angularVelocity: UnitIdentifier {
        return UnitIdentifier(rawValue: 0x2743)
    }
    
    /// period (beats per minute) (`0x27AF`)
    static var beatsPerMinute: UnitIdentifier {
        return UnitIdentifier(rawValue: 0x27AF)
    }
    
    /// length (mile) (`0x27A4`)
    static var mile: UnitIdentifier {
        return UnitIdentifier(rawValue: 0x27A4)
    }
    
    /// inductance (henry) (`0x272E`)
    static var inductance: UnitIdentifier {
        return UnitIdentifier(rawValue: 0x272E)
    }
    
    /// density (kilogram per cubic metre) (`0x2715`)
    static var density: UnitIdentifier {
        return UnitIdentifier(rawValue: 0x2715)
    }
    
    /// area (barn) (`0x2784`)
    static var barn: UnitIdentifier {
        return UnitIdentifier(rawValue: 0x2784)
    }
    
}
