//
//  HCILESetEventMask.swift
//  Bluetooth
//
//  Created by Alsey Coleman Miller on 6/13/18.
//  Copyright © 2018 PureSwift. All rights reserved.
//

// MARK: - BluetoothHostControllerInterface

#if !hasFeature(Embedded)
public extension BluetoothHostControllerInterface {

    /// LE Set Event Mask Command
    ///
    /// The command is used to control which LE events are generated by the HCI for the Host.
    func setLowEnergyEventMask(
        _ eventMask: HCILESetEventMask.EventMask,
        timeout: HCICommandTimeout = .default
    ) async throws {

        let parameter = HCILESetEventMask(eventMask: eventMask)

        try await deviceRequest(parameter, timeout: timeout)
    }
}
#endif

// MARK: - HCI Command

/// LE Set Event Mask Command
///
/// The command is used to control which LE events are generated by the HCI for the Host.
///
/// If the bit in the LE Event Mask is set to a one, then the event associated with that bit will be enabled.
/// The Host has to deal with each event that is generated by an LE Controller.
/// The event mask allows the Host to control which events will interrupt it.
///
/// For LE events to be generated, the LE Meta Event bit in the Event Mask shall also be set.
/// If that bit is not set, then LE events shall not be generated, regardless of how the LE Event Mask is set.
@frozen
public struct HCILESetEventMask: HCICommandParameter {

    public typealias EventMask = Event

    public static let command = HCILowEnergyCommand.setEventMask  // 0x0001

    /// The mask of LE events allowed to be generated by the HCI.
    public var eventMask: EventMask

    /// The value with all bits set to 0 indicates that no events are specified.
    /// The default is for bits 0 to 4 inclusive (the value 0x0000 0000 0000 001F) to be set.
    public init(eventMask: EventMask = Event(rawValue: 0x0000_0000_0000_001F)) {

        self.eventMask = eventMask
    }

    public func append<Data: DataContainer>(to data: inout Data) {

        let eventMaskBytes = eventMask.rawValue.littleEndian.bytes

        data += [
            eventMaskBytes.0,
            eventMaskBytes.1,
            eventMaskBytes.2,
            eventMaskBytes.3,
            eventMaskBytes.4,
            eventMaskBytes.5,
            eventMaskBytes.6,
            eventMaskBytes.7
        ]
    }
}

// MARK: - Supporting Types

public extension HCILESetEventMask {

    /// The value with all bits set to 0 indicates that no events are specified.
    /// The default is for bits 0 to 4 inclusive (the value `0x0000 0000 0000 001F`) to be set.
    ///
    /// All bits not listed in this table are reserved for future use.
    struct Event: OptionSet, Hashable, Sendable, CaseIterable, CustomStringConvertible {

        public let rawValue: UInt64

        public init(rawValue: UInt64) {
            self.rawValue = rawValue
        }

        /// LE Connection Complete Event
        public static let connectionComplete = Event(rawValue: 0b1)

        /// LE Advertising Report Event
        public static let advertisingReport = Event(rawValue: 0b10)

        /// LE Connection Update Complete Event
        public static let connectionUpdateComplete = Event(rawValue: 0b100)

        /// LE Read Remote Features Complete Event
        public static let readRemoteFeaturesComplete = Event(rawValue: 0b1000)

        /// LE Long Term Key Request Event
        public static let longTermKeyRequest = Event(rawValue: 0b10000)

        /// LE Remote Connection Parameter Request Event
        public static let remoteConnectionParameterRequest = Event(rawValue: 0b100000)

        /// LE Data Length Change Event
        public static let dataLengthChange = Event(rawValue: 0b1000000)

        /// LE Read Local P-256 Public Key Complete Event
        public static let readLocalP256PublicKeyComplete = Event(rawValue: 0b10000000)

        /// LE Generate DHKey Complete Event
        public static let generateDHKeyComplete = Event(rawValue: 0b1_00000000)

        /// LE Enhanced Connection Complete Event
        public static let enhancedConnectionComplete = Event(rawValue: 0b10_00000000)

        /// LE Directed Advertising Report Event
        public static let directedAdvertisingReport = Event(rawValue: 0b100_00000000)

        /// LE PHY Update Complete Event
        public static let phyUpdateComplete = Event(rawValue: 0b1000_00000000)

        /// LE Extended Advertising Report Event
        public static let extendedAdvertisingReport = Event(rawValue: 0b10000_00000000)

        /// LE Periodic Advertising Sync Established Event
        public static let periodicAdvertisingSyncEstablished = Event(rawValue: 0b100000_00000000)

        /// LE Periodic Advertising Report Event
        public static let periodicAdvertisingReport = Event(rawValue: 0b1000000_00000000)

        /// LE Periodic Advertising Sync Lost Event
        public static let periodicAdvertisingSyncLost = Event(rawValue: 0b10000000_00000000)

        /// LE Extended Scan Timeout Event
        public static let extendedScanTimeout = Event(rawValue: 0b1_00000000_00000000)

        /// LE Extended Advertising Set Terminated Event
        public static let extendedAdvertisingSetTerminated = Event(rawValue: 0b10_00000000_00000000)

        /// LE Scan Request Received Event
        public static let scanRequestReceived = Event(rawValue: 0b100_00000000_00000000)

        /// LE Channel Selection Algorithm Event
        public static let channelSelectionAlgorithm = Event(rawValue: 0b1000_00000000_00000000)

        /// LE Connectionless IQ Report Event
        public static let connectionlessIQReport = Event(rawValue: 0x10_0000)

        /// LE Connection IQ Report Event
        public static let connectionIQReport = Event(rawValue: 0x20_0000)

        /// LE CTE Request Failed Event
        public static let cteRequestFailed = Event(rawValue: 0x40_0000)

        /// LE Periodic Advertising Sync Transfer Received Event
        public static let periodicAdvertisingSyncTransferReceived = Event(rawValue: 0x80_0000)

        /// LE CIS Established Event
        public static let cisEstablished = Event(rawValue: 0x100_0000)

        /// LE CIS Request Event
        public static let cisRequest = Event(rawValue: 0x200_0000)

        /// LE Create BIG Complete Event
        public static let createBIGComplete = Event(rawValue: 0x400_0000)

        /// LE Terminate BIG Complete Event
        public static let terminateBIGComplete = Event(rawValue: 0x800_0000)

        /// LE BIG Sync Established Event
        public static let bigSyncEstablished = Event(rawValue: 0x1000_0000)

        /// LE BIG Sync Lost Event
        public static let bigSyncLost = Event(rawValue: 0x2000_0000)

        /// LE Request Peer SCA Complete Event
        public static let requestPeerSCAComplete = Event(rawValue: 0x4000_0000)

        /// LE Path Loss Threshold Event
        public static let pathLossThreshold = Event(rawValue: 0x8000_0000)

        /// LE Transmit Power Reporting Event
        public static let transmitPowerReporting = Event(rawValue: 0x1_0000_0000)

        /// LE BIGInfo Advertising Report Event
        public static let bigInfoAdvertisingReport = Event(rawValue: 0x2_0000_0000)

        /// LE Subrate Change Event
        public static let subrateChange = Event(rawValue: 0x4_0000_0000)

        /// LE Periodic Advertising Sync Established Event (v2)
        public static let periodicAdvertisingSyncEstablishedV2 = Event(rawValue: 0x8_0000_0000)

        /// LE Periodic Advertising Report Event (v2)
        public static let periodicAdvertisingReportV2 = Event(rawValue: 0x10_0000_0000)

        /// LE Periodic Advertising Sync Transfer Received Event (v2)
        public static let periodicAdvertisingSyncTransferReceivedV2 = Event(rawValue: 0x20_0000_0000)

        /// LE Periodic Advertising Subevent Data Request Event
        public static let periodicAdvertisingSubeventDataRequest = Event(rawValue: 0x40_0000_0000)

        /// LE Periodic Advertising Response Report Event
        public static let periodicAdvertisingResponseReport = Event(rawValue: 0x80_0000_0000)

        /// LE Enhanced Connection Complete Event (v2)
        public static let enhancedConnectionCompleteV2 = Event(rawValue: 0x100_0000_0000)

        /// LE CIS Established Event (v2)
        public static let cisEstablishedV2 = Event(rawValue: 0x200_0000_0000)

        /// LE Read All Remote Features Complete Event
        public static let readAllRemoteFeaturesComplete = Event(rawValue: 0x400_0000_0000)

        /// LE CS Read Remote Supported Capabilities Complete Event
        public static let csReadRemoteSupportedCapabilitiesComplete = Event(rawValue: 0x800_0000_0000)

        /// LE CS Read Remote FAE Table Complete Event
        public static let csReadRemoteFAETableComplete = Event(rawValue: 0x1000_0000_0000)

        /// LE CS Security Enable Complete Event
        public static let csSecurityEnableComplete = Event(rawValue: 0x2000_0000_0000)

        /// LE CS Config Complete Event
        public static let csConfigComplete = Event(rawValue: 0x4000_0000_0000)

        /// LE CS Procedure Enable Complete Event
        public static let csProcedureEnableComplete = Event(rawValue: 0x8000_0000_0000)

        /// LE CS Subevent Result Event
        public static let csSubeventResult = Event(rawValue: 0x1_0000_0000_0000)

        /// LE CS Subevent Result Continue Event
        public static let csSubeventResultContinue = Event(rawValue: 0x2_0000_0000_0000)

        /// LE CS Test End Complete Event
        public static let csTestEndComplete = Event(rawValue: 0x4_0000_0000_0000)

        /// LE Monitored Advertisers Report Event
        public static let monitoredAdvertisersReport = Event(rawValue: 0x8_0000_0000_0000)

        /// LE Frame Space Update Complete Event
        public static let frameSpaceUpdateComplete = Event(rawValue: 0x10_0000_0000_0000)

        /// LE UTP Receive Event
        public static let utpReceive = Event(rawValue: 0x20_0000_0000_0000)

        /// LE Connection Rate Change Event
        public static let connectionRateChange = Event(rawValue: 0x40_0000_0000_0000)

        /// LE CS Read Remote Supported Capabilities Complete Event (v2)
        public static let csReadRemoteSupportedCapabilitiesCompleteV2 = Event(rawValue: 0x80_0000_0000_0000)

        public static var allCases: [Event] {
            [
                .connectionComplete,
                .advertisingReport,
                .connectionUpdateComplete,
                .readRemoteFeaturesComplete,
                .longTermKeyRequest,
                .remoteConnectionParameterRequest,
                .dataLengthChange,
                .readLocalP256PublicKeyComplete,
                .generateDHKeyComplete,
                .enhancedConnectionComplete,
                .directedAdvertisingReport,
                .phyUpdateComplete,
                .extendedAdvertisingReport,
                .periodicAdvertisingSyncEstablished,
                .periodicAdvertisingReport,
                .periodicAdvertisingSyncLost,
                .extendedScanTimeout,
                .extendedAdvertisingSetTerminated,
                .scanRequestReceived,
                .channelSelectionAlgorithm,
                .connectionlessIQReport,
                .connectionIQReport,
                .cteRequestFailed,
                .periodicAdvertisingSyncTransferReceived,
                .cisEstablished,
                .cisRequest,
                .createBIGComplete,
                .terminateBIGComplete,
                .bigSyncEstablished,
                .bigSyncLost,
                .requestPeerSCAComplete,
                .pathLossThreshold,
                .transmitPowerReporting,
                .bigInfoAdvertisingReport,
                .subrateChange,
                .periodicAdvertisingSyncEstablishedV2,
                .periodicAdvertisingReportV2,
                .periodicAdvertisingSyncTransferReceivedV2,
                .periodicAdvertisingSubeventDataRequest,
                .periodicAdvertisingResponseReport,
                .enhancedConnectionCompleteV2,
                .cisEstablishedV2,
                .readAllRemoteFeaturesComplete,
                .csReadRemoteSupportedCapabilitiesComplete,
                .csReadRemoteFAETableComplete,
                .csSecurityEnableComplete,
                .csConfigComplete,
                .csProcedureEnableComplete,
                .csSubeventResult,
                .csSubeventResultContinue,
                .csTestEndComplete,
                .monitoredAdvertisersReport,
                .frameSpaceUpdateComplete,
                .utpReceive,
                .connectionRateChange,
                .csReadRemoteSupportedCapabilitiesCompleteV2
            ]
        }

        /// The equivalent `LowEnergyEvent`, if defined by this library.
        public var event: LowEnergyEvent? {

            switch self {

            case .connectionComplete: return .connectionComplete
            case .advertisingReport: return .advertisingReport
            case .connectionUpdateComplete: return .connectionUpdateComplete
            case .readRemoteFeaturesComplete: return .readRemoteUsedFeaturesComplete
            case .longTermKeyRequest: return .longTermKeyRequest
            case .remoteConnectionParameterRequest: return .remoteConnectionParameterRequest
            case .dataLengthChange: return .dataLengthChange
            case .readLocalP256PublicKeyComplete: return .readLocalP256PublicKeyComplete
            case .generateDHKeyComplete: return .generateDHKeyComplete
            case .enhancedConnectionComplete: return .enhancedConnectionComplete
            case .directedAdvertisingReport: return .directedAdvertisingReport
            case .phyUpdateComplete: return .phyUpdateComplete
            case .extendedAdvertisingReport: return .extendedAdvertisingReport
            case .periodicAdvertisingSyncEstablished: return .periodicAdvertisingSyncEstablished
            case .periodicAdvertisingReport: return .periodicAdvertisingReport
            case .periodicAdvertisingSyncLost: return .periodicAdvertisingSyncLost
            case .extendedScanTimeout: return .scanTimeout
            case .extendedAdvertisingSetTerminated: return .advertisingSetTerminated
            case .scanRequestReceived: return .scanRequestReceived
            case .channelSelectionAlgorithm: return .channelSelectionAlgorithm
            case .periodicAdvertisingSyncTransferReceived: return .periodicAdvertisingSyncTransferReceived
            case .periodicAdvertisingSyncEstablishedV2: return .periodicAdvertisingSyncEstablishedV2
            case .periodicAdvertisingReportV2: return .periodicAdvertisingReportV2
            case .periodicAdvertisingSyncTransferReceivedV2: return .periodicAdvertisingSyncTransferReceivedV2
            case .periodicAdvertisingSubeventDataRequest: return .periodicAdvertisingSubeventDataRequest
            case .periodicAdvertisingResponseReport: return .periodicAdvertisingResponseReport
            case .enhancedConnectionCompleteV2: return .enhancedConnectionCompleteV2
            default: return nil
            }
        }

        public var description: String {

            if let event = self.event {
                return event.description
            }

            switch self {
            case .connectionlessIQReport: return "LE Connectionless IQ Report Event"
            case .connectionIQReport: return "LE Connection IQ Report Event"
            case .cteRequestFailed: return "LE CTE Request Failed Event"
            case .cisEstablished: return "LE CIS Established Event"
            case .cisRequest: return "LE CIS Request Event"
            case .createBIGComplete: return "LE Create BIG Complete Event"
            case .terminateBIGComplete: return "LE Terminate BIG Complete Event"
            case .bigSyncEstablished: return "LE BIG Sync Established Event"
            case .bigSyncLost: return "LE BIG Sync Lost Event"
            case .requestPeerSCAComplete: return "LE Request Peer SCA Complete Event"
            case .pathLossThreshold: return "LE Path Loss Threshold Event"
            case .transmitPowerReporting: return "LE Transmit Power Reporting Event"
            case .bigInfoAdvertisingReport: return "LE BIGInfo Advertising Report Event"
            case .subrateChange: return "LE Subrate Change Event"
            case .cisEstablishedV2: return "LE CIS Established Event V2"
            case .readAllRemoteFeaturesComplete: return "LE Read All Remote Features Complete Event"
            case .csReadRemoteSupportedCapabilitiesComplete: return "LE CS Read Remote Supported Capabilities Complete Event"
            case .csReadRemoteFAETableComplete: return "LE CS Read Remote FAE Table Complete Event"
            case .csSecurityEnableComplete: return "LE CS Security Enable Complete Event"
            case .csConfigComplete: return "LE CS Config Complete Event"
            case .csProcedureEnableComplete: return "LE CS Procedure Enable Complete Event"
            case .csSubeventResult: return "LE CS Subevent Result Event"
            case .csSubeventResultContinue: return "LE CS Subevent Result Continue Event"
            case .csTestEndComplete: return "LE CS Test End Complete Event"
            case .monitoredAdvertisersReport: return "LE Monitored Advertisers Report Event"
            case .frameSpaceUpdateComplete: return "LE Frame Space Update Complete Event"
            case .utpReceive: return "LE UTP Receive Event"
            case .connectionRateChange: return "LE Connection Rate Change Event"
            case .csReadRemoteSupportedCapabilitiesCompleteV2: return "LE CS Read Remote Supported Capabilities Complete Event V2"
            default: return "LE Event (0x" + rawValue.toHexadecimal() + ")"
            }
        }
    }
}
