//
//  HCILESetEventMaskV2.swift
//  Bluetooth
//
//  Created by Alsey Coleman Miller on 7/9/26.
//  Copyright © 2026 PureSwift. All rights reserved.
//

// MARK: - BluetoothHostControllerInterface

#if !hasFeature(Embedded)
public extension BluetoothHostControllerInterface {

    /// LE Set Event Mask Command (v2)
    ///
    /// The command is used to control which LE events are generated by the HCI for the Host.
    ///
    /// Version 2 (Bluetooth 6.3, Running Out of Bits) widens the event mask from 8 octets
    /// to 255 octets and sets all bits of the mask, whereas the v1 command sets bits 0 to 63
    /// and leaves bits 64 and above unchanged.
    func setLowEnergyEventMaskV2(
        _ eventMask: HCILESetEventMask.EventMask,
        timeout: HCICommandTimeout = .default
    ) async throws {

        let parameter = HCILESetEventMaskV2(eventMask: eventMask)

        try await deviceRequest(parameter, timeout: timeout)
    }
}
#endif

// MARK: - HCI Command

/// LE Set Event Mask Command (v2)
///
/// The command is used to control which LE events are generated by the HCI for the Host.
///
/// Version 2 (Bluetooth 6.3, Running Out of Bits) widens the `LE_Event_Mask` parameter
/// from 8 octets to 255 octets. The v1 command sets bits 0 to 63 of the event mask and
/// leaves bits 64 and above unchanged; the v2 command sets all the bits of the event mask.
///
/// - Note: No LE events with a bit number of 64 or above have been assigned yet;
/// bits 64 and above are encoded as zero.
@frozen
public struct HCILESetEventMaskV2: HCICommandParameter {

    public typealias EventMask = HCILESetEventMask.EventMask

    public static let command = HCILowEnergyCommand.setEventMaskV2  // 0x00A4

    /// The length of the LE_Event_Mask parameter in octets.
    internal static let length = 255

    /// The mask of LE events allowed to be generated by the HCI.
    public var eventMask: EventMask

    /// The value with all bits set to 0 indicates that no events are specified.
    /// The default is for bits 0 to 4 inclusive (the value 0x0000 0000 0000 001F) to be set.
    public init(eventMask: EventMask = 0x0000_0000_0000_001F) {

        self.eventMask = eventMask
    }

    public func append<Data: DataContainer>(to data: inout Data) {

        let eventMaskBytes = eventMask.rawValue.littleEndian.bytes

        data += [
            eventMaskBytes.0,
            eventMaskBytes.1,
            eventMaskBytes.2,
            eventMaskBytes.3,
            eventMaskBytes.4,
            eventMaskBytes.5,
            eventMaskBytes.6,
            eventMaskBytes.7
        ]

        // bits 64 and above are not yet assigned
        data += repeatElement(0, count: Self.length - MemoryLayout<UInt64>.size)
    }
}
