//
//  HCISetEventMask.swift
//  Bluetooth
//
//  Created by Alsey Coleman Miller on 7/9/26.
//  Copyright © 2026 PureSwift. All rights reserved.
//

// MARK: - Method

#if !hasFeature(Embedded)
public extension BluetoothHostControllerInterface {

    /// Set Event Mask Command
    ///
    /// The command is used to control which events are generated by the HCI for the Host.
    ///
    /// If the bit in the Event_Mask is set to a one, then the event associated with that bit
    /// will be enabled. The Host has to deal with each event that is generated by a Controller.
    /// The event mask allows the Host to control how much it is interrupted.
    func setEventMask(
        _ eventMask: HCISetEventMask.EventMask,
        timeout: HCICommandTimeout = .default
    ) async throws {

        let parameter = HCISetEventMask(eventMask: eventMask)

        try await deviceRequest(parameter, timeout: timeout)
    }
}
#endif

// MARK: - Command

/// Set Event Mask Command
///
/// Used to control which events are generated by the HCI for the Host.
@frozen
public struct HCISetEventMask: HCICommandParameter {

    public typealias EventMask = BitMaskOptionSet<Event>

    public static let command = HostControllerBasebandCommand.setEventMask  // 0x0001

    /// The mask of events allowed to be generated by the HCI.
    public var eventMask: EventMask

    /// The default value is for bits 0 to 44 inclusive (the value `0x00001FFFFFFFFFFF`) to be set.
    public init(eventMask: EventMask = 0x0000_1FFF_FFFF_FFFF) {

        self.eventMask = eventMask
    }

    public func append<Data: DataContainer>(to data: inout Data) {

        let eventMaskBytes = eventMask.rawValue.littleEndian.bytes

        data += [
            eventMaskBytes.0,
            eventMaskBytes.1,
            eventMaskBytes.2,
            eventMaskBytes.3,
            eventMaskBytes.4,
            eventMaskBytes.5,
            eventMaskBytes.6,
            eventMaskBytes.7
        ]
    }
}

// MARK: - Supporting Types

public extension HCISetEventMask {

    /// Bit assignments of the Event_Mask parameter (Bluetooth Core Specification Vol 4, Part E, 7.3.1).
    ///
    /// Bits not listed here (13, 14, 18, 30, 35-42, 54, 57, 62, 63) are reserved for future use.
    enum Event: UInt64, BitMaskOption {

        /// Inquiry Complete Event
        case inquiryComplete = 0x1

        /// Inquiry Result Event
        case inquiryResult = 0x2

        /// Connection Complete Event
        case connectionComplete = 0x4

        /// Connection Request Event
        case connectionRequest = 0x8

        /// Disconnection Complete Event
        case disconnectionComplete = 0x10

        /// Authentication Complete Event
        case authenticationComplete = 0x20

        /// Remote Name Request Complete Event
        case remoteNameRequestComplete = 0x40

        /// Encryption Change Event
        case encryptionChange = 0x80

        /// Change Connection Link Key Complete Event
        case changeConnectionLinkKeyComplete = 0x100

        /// Master Link Key Complete Event
        case masterLinkKeyComplete = 0x200

        /// Read Remote Supported Features Complete Event
        case readRemoteSupportedFeaturesComplete = 0x400

        /// Read Remote Version Information Complete Event
        case readRemoteVersionInformationComplete = 0x800

        /// QoS Setup Complete Event
        case qosSetupComplete = 0x1000

        /// Hardware Error Event
        case hardwareError = 0x8000

        /// Flush Occurred Event
        case flushOccurred = 0x1_0000

        /// Role Change Event
        case roleChange = 0x2_0000

        /// Mode Change Event
        case modeChange = 0x8_0000

        /// Return Link Keys Event
        case returnLinkKeys = 0x10_0000

        /// PIN Code Request Event
        case pinCodeRequest = 0x20_0000

        /// Link Key Request Event
        case linkKeyRequest = 0x40_0000

        /// Link Key Notification Event
        case linkKeyNotification = 0x80_0000

        /// Loopback Command Event
        case loopbackCommand = 0x100_0000

        /// Data Buffer Overflow Event
        case dataBufferOverflow = 0x200_0000

        /// Max Slots Change Event
        case maxSlotsChange = 0x400_0000

        /// Read Clock Offset Complete Event
        case readClockOffsetComplete = 0x800_0000

        /// Connection Packet Type Changed Event
        case connectionPacketTypeChanged = 0x1000_0000

        /// QoS Violation Event
        case qosViolation = 0x2000_0000

        /// Page Scan Repetition Mode Change Event
        case pageScanRepetitionModeChange = 0x8000_0000

        /// Flow Specification Complete Event
        case flowSpecificationComplete = 0x1_0000_0000

        /// Inquiry Result with RSSI Event
        case inquiryResultWithRSSI = 0x2_0000_0000

        /// Read Remote Extended Features Complete Event
        case readRemoteExtendedFeaturesComplete = 0x4_0000_0000

        /// Synchronous Connection Complete Event
        case synchronousConnectionComplete = 0x800_0000_0000

        /// Synchronous Connection Changed Event
        case synchronousConnectionChanged = 0x1000_0000_0000

        /// Sniff Subrating Event
        case sniffSubrating = 0x2000_0000_0000

        /// Extended Inquiry Result Event
        case extendedInquiryResult = 0x4000_0000_0000

        /// Encryption Key Refresh Complete Event
        case encryptionKeyRefreshComplete = 0x8000_0000_0000

        /// IO Capability Request Event
        case ioCapabilityRequest = 0x1_0000_0000_0000

        /// IO Capability Response Event
        case ioCapabilityResponse = 0x2_0000_0000_0000

        /// User Confirmation Request Event
        case userConfirmationRequest = 0x4_0000_0000_0000

        /// User Passkey Request Event
        case userPasskeyRequest = 0x8_0000_0000_0000

        /// Remote OOB Data Request Event
        case remoteOOBDataRequest = 0x10_0000_0000_0000

        /// Simple Pairing Complete Event
        case simplePairingComplete = 0x20_0000_0000_0000

        /// Link Supervision Timeout Changed Event
        case linkSupervisionTimeoutChanged = 0x80_0000_0000_0000

        /// Enhanced Flush Complete Event
        case enhancedFlushComplete = 0x100_0000_0000_0000

        /// User Passkey Notification Event
        case userPasskeyNotification = 0x400_0000_0000_0000

        /// Keypress Notification Event
        case keypressNotification = 0x800_0000_0000_0000

        /// Remote Host Supported Features Notification Event
        case remoteHostSupportedFeaturesNotification = 0x1000_0000_0000_0000

        /// LE Meta Event
        ///
        /// For LE events to be generated, this bit shall also be set.
        /// If this bit is not set, then LE events shall not be generated, regardless of how the
        /// LE Event Mask (see LE Set Event Mask command) is set.
        case lowEnergyMeta = 0x2000_0000_0000_0000

        public static var allCases: [Event] {
            [
                .inquiryComplete,
                .inquiryResult,
                .connectionComplete,
                .connectionRequest,
                .disconnectionComplete,
                .authenticationComplete,
                .remoteNameRequestComplete,
                .encryptionChange,
                .changeConnectionLinkKeyComplete,
                .masterLinkKeyComplete,
                .readRemoteSupportedFeaturesComplete,
                .readRemoteVersionInformationComplete,
                .qosSetupComplete,
                .hardwareError,
                .flushOccurred,
                .roleChange,
                .modeChange,
                .returnLinkKeys,
                .pinCodeRequest,
                .linkKeyRequest,
                .linkKeyNotification,
                .loopbackCommand,
                .dataBufferOverflow,
                .maxSlotsChange,
                .readClockOffsetComplete,
                .connectionPacketTypeChanged,
                .qosViolation,
                .pageScanRepetitionModeChange,
                .flowSpecificationComplete,
                .inquiryResultWithRSSI,
                .readRemoteExtendedFeaturesComplete,
                .synchronousConnectionComplete,
                .synchronousConnectionChanged,
                .sniffSubrating,
                .extendedInquiryResult,
                .encryptionKeyRefreshComplete,
                .ioCapabilityRequest,
                .ioCapabilityResponse,
                .userConfirmationRequest,
                .userPasskeyRequest,
                .remoteOOBDataRequest,
                .simplePairingComplete,
                .linkSupervisionTimeoutChanged,
                .enhancedFlushComplete,
                .userPasskeyNotification,
                .keypressNotification,
                .remoteHostSupportedFeaturesNotification,
                .lowEnergyMeta
            ]
        }
    }
}
