//
//  HCISetEventMask.swift
//  Bluetooth
//
//  Created by Alsey Coleman Miller on 7/9/26.
//  Copyright © 2026 PureSwift. All rights reserved.
//

// MARK: - Method

#if !hasFeature(Embedded)
public extension BluetoothHostControllerInterface {

    /// Set Event Mask Command
    ///
    /// The command is used to control which events are generated by the HCI for the Host.
    ///
    /// If the bit in the Event_Mask is set to a one, then the event associated with that bit
    /// will be enabled. The Host has to deal with each event that is generated by a Controller.
    /// The event mask allows the Host to control how much it is interrupted.
    func setEventMask(
        _ eventMask: HCISetEventMask.EventMask,
        timeout: HCICommandTimeout = .default
    ) async throws {

        let parameter = HCISetEventMask(eventMask: eventMask)

        try await deviceRequest(parameter, timeout: timeout)
    }
}
#endif

// MARK: - Command

/// Set Event Mask Command
///
/// Used to control which events are generated by the HCI for the Host.
@frozen
public struct HCISetEventMask: HCICommandParameter {

    public typealias EventMask = Event

    public static let command = HostControllerBasebandCommand.setEventMask  // 0x0001

    /// The mask of events allowed to be generated by the HCI.
    public var eventMask: EventMask

    /// The default value is for bits 0 to 44 inclusive (the value `0x00001FFFFFFFFFFF`) to be set.
    public init(eventMask: EventMask = Event(rawValue: 0x0000_1FFF_FFFF_FFFF)) {

        self.eventMask = eventMask
    }

    public func append<Data: DataContainer>(to data: inout Data) {

        let eventMaskBytes = eventMask.rawValue.littleEndian.bytes

        data += [
            eventMaskBytes.0,
            eventMaskBytes.1,
            eventMaskBytes.2,
            eventMaskBytes.3,
            eventMaskBytes.4,
            eventMaskBytes.5,
            eventMaskBytes.6,
            eventMaskBytes.7
        ]
    }
}

// MARK: - Supporting Types

public extension HCISetEventMask {

    /// Bit assignments of the Event_Mask parameter (Bluetooth Core Specification Vol 4, Part E, 7.3.1).
    ///
    /// Bits not listed here (13, 14, 18, 30, 35-42, 54, 57, 62, 63) are reserved for future use.
    struct Event: OptionSet, Hashable, Sendable, CaseIterable {

        public let rawValue: UInt64

        public init(rawValue: UInt64) {
            self.rawValue = rawValue
        }

        /// Inquiry Complete Event
        public static let inquiryComplete = Event(rawValue: 0x1)

        /// Inquiry Result Event
        public static let inquiryResult = Event(rawValue: 0x2)

        /// Connection Complete Event
        public static let connectionComplete = Event(rawValue: 0x4)

        /// Connection Request Event
        public static let connectionRequest = Event(rawValue: 0x8)

        /// Disconnection Complete Event
        public static let disconnectionComplete = Event(rawValue: 0x10)

        /// Authentication Complete Event
        public static let authenticationComplete = Event(rawValue: 0x20)

        /// Remote Name Request Complete Event
        public static let remoteNameRequestComplete = Event(rawValue: 0x40)

        /// Encryption Change Event
        public static let encryptionChange = Event(rawValue: 0x80)

        /// Change Connection Link Key Complete Event
        public static let changeConnectionLinkKeyComplete = Event(rawValue: 0x100)

        /// Master Link Key Complete Event
        public static let masterLinkKeyComplete = Event(rawValue: 0x200)

        /// Read Remote Supported Features Complete Event
        public static let readRemoteSupportedFeaturesComplete = Event(rawValue: 0x400)

        /// Read Remote Version Information Complete Event
        public static let readRemoteVersionInformationComplete = Event(rawValue: 0x800)

        /// QoS Setup Complete Event
        public static let qosSetupComplete = Event(rawValue: 0x1000)

        /// Hardware Error Event
        public static let hardwareError = Event(rawValue: 0x8000)

        /// Flush Occurred Event
        public static let flushOccurred = Event(rawValue: 0x1_0000)

        /// Role Change Event
        public static let roleChange = Event(rawValue: 0x2_0000)

        /// Mode Change Event
        public static let modeChange = Event(rawValue: 0x8_0000)

        /// Return Link Keys Event
        public static let returnLinkKeys = Event(rawValue: 0x10_0000)

        /// PIN Code Request Event
        public static let pinCodeRequest = Event(rawValue: 0x20_0000)

        /// Link Key Request Event
        public static let linkKeyRequest = Event(rawValue: 0x40_0000)

        /// Link Key Notification Event
        public static let linkKeyNotification = Event(rawValue: 0x80_0000)

        /// Loopback Command Event
        public static let loopbackCommand = Event(rawValue: 0x100_0000)

        /// Data Buffer Overflow Event
        public static let dataBufferOverflow = Event(rawValue: 0x200_0000)

        /// Max Slots Change Event
        public static let maxSlotsChange = Event(rawValue: 0x400_0000)

        /// Read Clock Offset Complete Event
        public static let readClockOffsetComplete = Event(rawValue: 0x800_0000)

        /// Connection Packet Type Changed Event
        public static let connectionPacketTypeChanged = Event(rawValue: 0x1000_0000)

        /// QoS Violation Event
        public static let qosViolation = Event(rawValue: 0x2000_0000)

        /// Page Scan Repetition Mode Change Event
        public static let pageScanRepetitionModeChange = Event(rawValue: 0x8000_0000)

        /// Flow Specification Complete Event
        public static let flowSpecificationComplete = Event(rawValue: 0x1_0000_0000)

        /// Inquiry Result with RSSI Event
        public static let inquiryResultWithRSSI = Event(rawValue: 0x2_0000_0000)

        /// Read Remote Extended Features Complete Event
        public static let readRemoteExtendedFeaturesComplete = Event(rawValue: 0x4_0000_0000)

        /// Synchronous Connection Complete Event
        public static let synchronousConnectionComplete = Event(rawValue: 0x800_0000_0000)

        /// Synchronous Connection Changed Event
        public static let synchronousConnectionChanged = Event(rawValue: 0x1000_0000_0000)

        /// Sniff Subrating Event
        public static let sniffSubrating = Event(rawValue: 0x2000_0000_0000)

        /// Extended Inquiry Result Event
        public static let extendedInquiryResult = Event(rawValue: 0x4000_0000_0000)

        /// Encryption Key Refresh Complete Event
        public static let encryptionKeyRefreshComplete = Event(rawValue: 0x8000_0000_0000)

        /// IO Capability Request Event
        public static let ioCapabilityRequest = Event(rawValue: 0x1_0000_0000_0000)

        /// IO Capability Response Event
        public static let ioCapabilityResponse = Event(rawValue: 0x2_0000_0000_0000)

        /// User Confirmation Request Event
        public static let userConfirmationRequest = Event(rawValue: 0x4_0000_0000_0000)

        /// User Passkey Request Event
        public static let userPasskeyRequest = Event(rawValue: 0x8_0000_0000_0000)

        /// Remote OOB Data Request Event
        public static let remoteOOBDataRequest = Event(rawValue: 0x10_0000_0000_0000)

        /// Simple Pairing Complete Event
        public static let simplePairingComplete = Event(rawValue: 0x20_0000_0000_0000)

        /// Link Supervision Timeout Changed Event
        public static let linkSupervisionTimeoutChanged = Event(rawValue: 0x80_0000_0000_0000)

        /// Enhanced Flush Complete Event
        public static let enhancedFlushComplete = Event(rawValue: 0x100_0000_0000_0000)

        /// User Passkey Notification Event
        public static let userPasskeyNotification = Event(rawValue: 0x400_0000_0000_0000)

        /// Keypress Notification Event
        public static let keypressNotification = Event(rawValue: 0x800_0000_0000_0000)

        /// Remote Host Supported Features Notification Event
        public static let remoteHostSupportedFeaturesNotification = Event(rawValue: 0x1000_0000_0000_0000)

        /// LE Meta Event
        ///
        /// For LE events to be generated, this bit shall also be set.
        /// If this bit is not set, then LE events shall not be generated, regardless of how the
        /// LE Event Mask (see LE Set Event Mask command) is set.
        public static let lowEnergyMeta = Event(rawValue: 0x2000_0000_0000_0000)

        public static var allCases: [Event] {
            [
                .inquiryComplete,
                .inquiryResult,
                .connectionComplete,
                .connectionRequest,
                .disconnectionComplete,
                .authenticationComplete,
                .remoteNameRequestComplete,
                .encryptionChange,
                .changeConnectionLinkKeyComplete,
                .masterLinkKeyComplete,
                .readRemoteSupportedFeaturesComplete,
                .readRemoteVersionInformationComplete,
                .qosSetupComplete,
                .hardwareError,
                .flushOccurred,
                .roleChange,
                .modeChange,
                .returnLinkKeys,
                .pinCodeRequest,
                .linkKeyRequest,
                .linkKeyNotification,
                .loopbackCommand,
                .dataBufferOverflow,
                .maxSlotsChange,
                .readClockOffsetComplete,
                .connectionPacketTypeChanged,
                .qosViolation,
                .pageScanRepetitionModeChange,
                .flowSpecificationComplete,
                .inquiryResultWithRSSI,
                .readRemoteExtendedFeaturesComplete,
                .synchronousConnectionComplete,
                .synchronousConnectionChanged,
                .sniffSubrating,
                .extendedInquiryResult,
                .encryptionKeyRefreshComplete,
                .ioCapabilityRequest,
                .ioCapabilityResponse,
                .userConfirmationRequest,
                .userPasskeyRequest,
                .remoteOOBDataRequest,
                .simplePairingComplete,
                .linkSupervisionTimeoutChanged,
                .enhancedFlushComplete,
                .userPasskeyNotification,
                .keypressNotification,
                .remoteHostSupportedFeaturesNotification,
                .lowEnergyMeta
            ]
        }
    }
}
