#!/usr/bin/env python3
"""
Generate `Sources/BluetoothABI/gen/CompanyNames.swift` from the Bluetooth
SIG assigned-numbers metadata.

`bt_compidtostr` returns `const char *` with static lifetime. Rather than
depend on Foundation, `Bundle.module` and a runtime-initialized
dictionary — none of which are available to the CMake build or to
Embedded Swift — the whole table is baked into the binary as a single
NUL-separated `StaticString` blob plus an integer switch mapping company
identifier to blob offset. Lookups are then a jump table and a pointer
add, with no allocation and no global initializer.

Usage:
    Scripts/generate-company-names.py

Re-run after updating Sources/BluetoothMetadata/Resources/CompanyIdentifier.json
and commit the result.
"""

import json
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SOURCE = os.path.join(
    ROOT, "Sources", "BluetoothMetadata", "Resources", "CompanyIdentifier.json"
)
OUTPUT = os.path.join(ROOT, "Sources", "BluetoothABI", "gen", "CompanyNames.swift")

# Matches the reference `bt_compidtostr` fallbacks in BlueZ lib/bluetooth.c.
INTERNAL_USE_ID = 65535
INTERNAL_USE = "internal use"
NOT_ASSIGNED = "not assigned"

HEADER = '''//
//  CompanyNames.swift
//  Bluetooth
//
//  Generated by Scripts/generate-company-names.py — do not edit.
//
//  Source: Sources/BluetoothMetadata/Resources/CompanyIdentifier.json
//  ({count} assigned identifiers)
//
//  The names are stored as one NUL-separated blob so that every entry is
//  a valid C string with static lifetime, as `bt_compidtostr` requires,
//  without any runtime initialization.
//

'''


def swift_escape(text):
    """Escape a string for inclusion in a Swift string literal."""
    out = []
    for char in text:
        if char == "\\":
            out.append("\\\\")
        elif char == '"':
            out.append('\\"')
        elif char == "\n":
            out.append("\\n")
        elif char == "\t":
            out.append("\\t")
        elif ord(char) < 0x20 or ord(char) == 0x7F:
            out.append("\\u{%X}" % ord(char))
        else:
            out.append(char)
    return "".join(out)


def load_identifiers():
    with open(SOURCE, encoding="utf-8") as handle:
        document = json.load(handle)

    entries = document.get("company_identifiers")
    if entries is None:
        # The file is a single-key object; take whatever list it holds.
        entries = next(value for value in document.values() if isinstance(value, list))

    table = {}
    for entry in entries:
        identifier = entry.get("value", entry.get("id"))
        name = entry["name"]
        if identifier is None:
            continue
        table[int(identifier)] = name
    return table


def main():
    table = load_identifiers()

    # Both fallbacks live in the blob too, so every returned pointer comes
    # from the same static allocation.
    names = [INTERNAL_USE, NOT_ASSIGNED]
    names.extend(table[key] for key in sorted(table))

    # De-duplicate: many companies share a name across identifiers.
    offsets = {}
    blob = []
    length = 0
    for name in names:
        if name in offsets:
            continue
        offsets[name] = length
        blob.append(swift_escape(name))
        length += len(name.encode("utf-8")) + 1

    lines = [HEADER.format(count=len(table))]
    lines.append("/// Company names, NUL-separated.\n")
    lines.append('private let blob: StaticString = "%s\\0"\n\n' % "\\0".join(blob))
    lines.append("/// The offset of `\"%s\"` within `blob`.\n" % INTERNAL_USE)
    lines.append(
        "internal let internalUseOffset = %d\n\n" % offsets[INTERNAL_USE]
    )
    lines.append("/// The offset of `\"%s\"` within `blob`.\n" % NOT_ASSIGNED)
    lines.append("internal let notAssignedOffset = %d\n\n" % offsets[NOT_ASSIGNED])
    lines.append(
        "/// The C string at `offset` within the name blob. The pointer has\n"
        "/// static lifetime, as `bt_compidtostr` requires.\n"
        "internal func companyName(at offset: Int) -> UnsafePointer<CChar> {\n"
        "    UnsafeRawPointer(blob.utf8Start + offset)\n"
        "        .assumingMemoryBound(to: CChar.self)\n"
        "}\n\n"
    )
    lines.append(
        "/// The blob offset of the name assigned to `id`, or `nil` if the\n"
        "/// Bluetooth SIG has no current assignment for it.\n"
        "internal func companyNameOffset(for id: UInt16) -> Int? {\n"
        "    switch id {\n"
    )
    for key in sorted(table):
        lines.append("    case %d: return %d\n" % (key, offsets[table[key]]))
    lines.append("    default: return nil\n    }\n}\n")

    os.makedirs(os.path.dirname(OUTPUT), exist_ok=True)
    with open(OUTPUT, "w", encoding="utf-8") as handle:
        handle.write("".join(lines))

    print(
        "wrote %s (%d identifiers, %d unique names, %d byte blob)"
        % (
            os.path.relpath(OUTPUT, ROOT),
            len(table),
            len(blob),
            length,
        )
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
