name: Documentation

on: [push]

jobs:

    bluetooth-docs:
        name: Bluetooth Documentation
        runs-on: macOS-latest
        steps:
        - name: Checkout
          uses: actions/checkout@v1
        - name: Xcode Version
          run: |
            sudo xcode-select -s /Applications/Xcode_11.3.1.app
            xcodebuild -version
            swift --version
        - name: Swift Version
          run: swift --version
        - name: Jazzy
          run: jazzy
        - name: Upload docs
          uses: actions/upload-artifact@v1
          if: always()
          with:
            name: docs
            path: docs
