name: Swift Lint
on: [pull_request]
jobs:
    swift-format-lint:
      name: swift-format lint
      runs-on: ubuntu-latest
      container: swift:6.0.3
      steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Swift Version
        run: swift --version
      - name: Lint
        run: swift format lint -r ./ --configuration .swift-format
  
    swiftlint:
      name: swiftlint 
      runs-on: macos-latest
      steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Swift
        uses: slashmo/install-swift@v0.4.0
        with:
          version: 6.0.3
      - name: Swift Version
        run: swift --version
      - name: Install SwiftLint
        run: brew install swiftlint
      - name: Lint
        run: swiftlint
