name: Swift Lint
on: [pull_request]
jobs:
    swift-format-lint:
      name: swift-format lint
      runs-on: ubuntu-latest
      container: swift:6.0.3
      steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Swift Version
        run: swift --version
      - name: Lint
        run: swift format lint -r ./ --configuration .swift-format
  
